services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      target: builder
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  celery_worker:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
